PrismaWEB.MVC/ViewModels/PessoaViewModel.cs
using ProjetoModeloDDD.Domain.Attribute;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace ProjetoModeloDDD.MVC.ViewModels
{
    public class PessoaViewModel
    {
        [Key]
        public int Id { get; set; }

        [Required]
        [MaxLength(60)]
        public string Nome { get; set; }

        [Required]
        [Display(Name = "Data Nascimento")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd-MM-yyyy}")]
        [DataType(DataType.Date, ErrorMessage = "Data em formato inválido")]
        public DateTime DataNascimento { get; set; }

        [Required]
        [Cpf(ErrorMessage = "CPF Inválido")]
        [Display(Name = "CPF")]       
        public string Cpf { get; set; }

        [DataType(DataType.Upload)]
        public string Foto { get; set; }

        [Required]
        [Display(Name = "Usuario Ativo")]
        public bool Ativo { get; set; }

        [Required]
        [Display(Name = "E-mail")]
        [EmailAddress]
        [StringLength(60, MinimumLength = 5)]
        public string Email { get; set; }

        [Required]
        public string Apelido { get; set; }

        [Display(Name = "Telefone Fixo")]
        public string TelefoneFixo { get; set; }

        [Display(Name = "Telefone Movel")]
        public string TelefoneMovel { get; set; }

        [Required]
        [Display(Name = "País")]
        public int Pais_Id { get; set; }

        [Required]
        [Display(Name = "Estado")]
        public int Estado_Id { get; set; }

        [Required]
        [Display(Name = "Cidade")]
        public int Cidade_Id { get; set; }

        [Display(Name = "Bairro")]
        public int Bairro_Id { get; set; }

        [Display(Name = "Logradouro")]
        public int Logradouro_Id { get; set; }

        [MaxLength(8)]
        public string Cep { get; set; }

        [MaxLength(6)]
        public string Numero { get; set; }
        
        [MaxLength(250)]
        public string Complemento { get; set; }

        public int Tipo_Id { get; set; }

        public TipoPessoaViewModel Tipo { get; set; }

        public virtual BairroViewModel Bairro { get; set; }
        //public virtual CidadeViewModel Cidade { get; set; }
        //public virtual EstadoViewModel Estado { get; set; }
        public virtual LogradouroViewModel Logradouro { get; set; }
        public virtual PaisViewModel Pais { get; set; }
    }
}

PrismaWEB.MVC/Controllers/BotoesController.cs
using AutoMapper;
using ProjetoModeloDDD.Application.Interface;
using ProjetoModeloDDD.Domain.Entities;
using ProjetoModeloDDD.MVC.Helpers.Armazenamento;
using ProjetoModeloDDD.MVC.ViewModels;
using ProjetoModeloDDD.MVC.ViewModels.Sistema;
using System.Collections.Generic;
using System.Web.Mvc;

namespace ProjetoModeloDDD.MVC.Controllers
{
    public class BotoesController : Controller
    {
        private readonly ISPapeisAcoesAppService _PapeisAcoesApp;

        public BotoesController(ISPapeisAcoesAppService PapeisAcoesApp)
        {
            _PapeisAcoesApp = PapeisAcoesApp;
        }

        // GET: Botoes
        public ActionResult BotaoCreate(string NomeController)
        {
            var usuario = ArmazemSession.Buscar("usuarioLogado") as SCadastroUsuarioLogadoViewModel;
            var papeisVM = usuario.Papeis;

            var papeis = Mapper.Map<IEnumerable<SPapelViewModel>, IList<SPapel>>(papeisVM);

            ViewBag.NomeController = NomeController;
            ViewBag.Visivel = _PapeisAcoesApp.PapeisTemAcessoAcao(papeis, NomeController);            
            return View();
        }
    }
}

PrismaWEB.MVC/Controllers/PessoasController.cs
using AutoMapper;
using PrismaWEB.Utils.Exception;
using ProjetoModeloDDD.Application.Interface;
using ProjetoModeloDDD.Domain.Entities;
using ProjetoModeloDDD.MVC.ViewModels;
using ProjetoModeloDDD.MVC.ViewModels.Sistema;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace ProjetoModeloDDD.MVC.Controllers
{
    public class PessoasController : Controller
    {
        private readonly IPessoaAppService _pessoaApp;
        private readonly ISCadastroAppService _cadastroApp;
        private readonly IPaisAppService _paisApp;
        private readonly IEstadoAppService _estadoApp;
        private readonly ICidadeAppService _cidadeApp;
        private readonly IBairroAppService _bairroApp;
        private readonly ILogradouroAppService _logradouroApp;


        public PessoasController(IPessoaAppService pessoaApp,
                                 ISCadastroAppService cadastroApp,
                                 IPaisAppService paisApp,
                                 IEstadoAppService estadoApp,
                                 ICidadeAppService cidadeApp,
                                 IBairroAppService bairroApp,
                                 ILogradouroAppService logradouroApp)
        {
            _pessoaApp = pessoaApp;
            _cadastroApp = cadastroApp;
            _paisApp = paisApp;
            _estadoApp = estadoApp;
            _cidadeApp = cidadeApp;
            _bairroApp = bairroApp;
            _logradouroApp = logradouroApp;
        }

        // GET: Pessoas
        public ActionResult Index()
        {
            var pessoaViewModel = Mapper.Map<IEnumerable<Pessoa>, IEnumerable<PessoaViewModel>>(_pessoaApp.GetAll());
            return View(pessoaViewModel);
        }

        // GET: Pessoas/Details/5
        public ActionResult Details(int id)
        {
            var pessoa = _pessoaApp.GetById(id);
            var pessoaViewModel = Mapper.Map<Pessoa, PessoaViewModel>(pessoa);
            return View(pessoaViewModel);
        }

        // GET: Pessoas/Create
        public ActionResult Create()
        {            
            ViewBag.Pais_Id = new SelectList(_paisApp.GetAll(), "Id", "Nome");
            ViewBag.Estado_Id = new SelectList(_estadoApp.GetAll(), "Id", "Nome");
            ViewBag.Cidade_Id = new SelectList(_cidadeApp.GetAll(), "Id", "Nome");
            ViewBag.Bairro_Id = new SelectList(_bairroApp.GetAll(), "Id", "Nome");
            ViewBag.Logradouro_Id = new SelectList(_logradouroApp.GetAll(), "Id", "Nome");

            return View();
        }

        // POST: Pessoas/Create
        [HttpPost]
        public ActionResult Create(SPessoaCadastroViewModel pessoaCadastro)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var cadastroD = pessoaCadastro.MontaCadastro();
                    var pessoaD = pessoaCadastro.MontaPessoa();

                    _pessoaApp.AddPesoaComCadastro(pessoaD, cadastroD);
                    return RedirectToAction("Index");
                }

            }
            catch (ListEntidadeException exp)
            {
                foreach (var item in exp.Exceptions)
                {
                    ModelState.AddModelError(item.NomeCampo, item.Message);
                }                    
            }
            catch (EntidadeException exp)
            {
                ModelState.AddModelError(exp.NomeCampo, exp.Message);
            }

            ViewBag.Pais_Id = new SelectList(_paisApp.GetAll(), "Id", "Nome", pessoaCadastro.Pais_Id);
            ViewBag.Estado_Id = new SelectList(_estadoApp.GetAll(), "Id", "Nome", pessoaCadastro.Estado_Id);
            ViewBag.Cidade_Id = new SelectList(_cidadeApp.GetAll(), "Id", "Nome", pessoaCadastro.Cidade_Id);
            ViewBag.Bairro_Id = new SelectList(_bairroApp.GetAll(), "Id", "Nome", pessoaCadastro.Bairro_Id);
            ViewBag.Logradouro_Id = new SelectList(_logradouroApp.GetAll(), "Id", "Nome", pessoaCadastro.Logradouro_Id);
            return View(pessoaCadastro);
        }

        // GET: Pessoas/Edit/5
        public ActionResult Edit(int id)
        {
            ViewBag.Pais_Id = new SelectList(_paisApp.GetAll(), "Id", "Nome");
            ViewBag.Estado_Id = new SelectList(_estadoApp.GetAll(), "Id", "Nome");
            ViewBag.Cidade_Id = new SelectList(_cidadeApp.GetAll(), "Id", "Nome");
            ViewBag.Bairro_Id = new SelectList(_bairroApp.GetAll(), "Id", "Nome");
            ViewBag.Logradouro_Id = new SelectList(_logradouroApp.GetAll(), "Id", "Nome");

            var pessoa = _pessoaApp.GetById(id);
            var pessoaCadastroViewModel = Mapper.Map<Pessoa, SPessoaCadastroViewModel>(pessoa);

            var cadastro = _cadastroApp.BuscaCadastroPorPessoa(id);

            if (cadastro != null)
            {
                pessoaCadastroViewModel.Login = cadastro.Login;
                pessoaCadastroViewModel.Senha = "********";
                pessoaCadastroViewModel.ValidaSenha = "********";
            }

            return View(pessoaCadastroViewModel);
        }

        // POST: Pessoas/Edit/5
        [HttpPost]
        public ActionResult Edit(SPessoaCadastroViewModel pessoaCadastro)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var pessoaD = pessoaCadastro.MontaPessoa();
                    var cadastroD = pessoaCadastro.MontaCadastro();

                    _pessoaApp.Update(pessoaD);                    
                    if (cadastroD != null)
                    {
                        if (cadastroD.Senha == "********")
                            cadastroD.Senha = null;

                        cadastroD.Pessoa_Id = pessoaD.Id;
                        _cadastroApp.Update(cadastroD);
                    }
                    return RedirectToAction("Index");
                }
            }
            catch (ListEntidadeException exps)
            {
                foreach (var exp in exps.Exceptions)
                {
                    ModelState.AddModelError(exp.NomeCampo, exp.Message);
                }
            }
            catch (EntidadeException exp)
            {
                ModelState.AddModelError(exp.NomeCampo, exp.Message);
            }
            catch (Exception exp)
            {
                if (exp.InnerException != null)
                    ModelState.AddModelError(string.Empty, exp.InnerException.InnerException.Message);

            }
            ViewBag.Pais_Id = new SelectList(_paisApp.GetAll(), "Id", "Nome", pessoaCadastro.Pais_Id);
            ViewBag.Estado_Id = new SelectList(_estadoApp.GetAll(), "Id", "Nome", pessoaCadastro.Estado_Id);
            ViewBag.Cidade_Id = new SelectList(_cidadeApp.GetAll(), "Id", "Nome", pessoaCadastro.Cidade_Id);
            ViewBag.Bairro_Id = new SelectList(_bairroApp.GetAll(), "Id", "Nome", pessoaCadastro.Bairro_Id);
            ViewBag.Logradouro_Id = new SelectList(_logradouroApp.GetAll(), "Id", "Nome", pessoaCadastro.Logradouro_Id);
            return View(pessoaCadastro);
        }

        public ActionResult Desativar(int id)
        {
            _pessoaApp.DesativarPessoa(id);
            return RedirectToAction("Index");
        }

        public ActionResult Ativar(int id)
        {
            _pessoaApp.AtivarPessoa(id);
            return RedirectToAction("Index");
        }

        // GET: Pessoas/Delete/5
        public JsonResult Delete(int id)
        {
            try
            {
                _pessoaApp.Remove(_pessoaApp.GetById(id));
                return Json(404);
            }
            catch (Exception exp)
            {
                return Json(exp.Message);
            }            
        }
    }
}

PrismaWEB.MVC/Views/Pessoas/Create.cshtml
@model ProjetoModeloDDD.MVC.ViewModels.Sistema.SPessoaCadastroViewModel

@{
    ViewBag.Title = "Create";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-row col-12">
        <div class="form-group col-12">
            <div class="col-md-offset-2">
                <input type="submit" value="Salvar" class="ui violet button" />
                <input id="SaveAndNew" type="submit" value="Salvar/Novo" class="ui blue button" />
                <a href="@Url.Action("Index")" class="ui grey button">Cancelar</a>
            </div>
        </div>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <h4 class="ui dividing header" style="width: 100%">Dados Pessoais</h4>

        <div class="form-group col-md-6">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label" })
            <label style="color:red;" title="Campo obrigatório">*</label>
            <div class="ui-widget">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group col-md-3">
            @Html.LabelFor(model => model.DataNascimento, htmlAttributes: new { @class = "control-label" })
            <label style="color:red;" title="Campo obrigatório">*</label>
            <div class="ui-widget">
                @Html.EditorFor(model => model.DataNascimento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DataNascimento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group col-md-3">
            @Html.LabelFor(model => model.Cpf, htmlAttributes: new { @class = "control-label" })
            <label style="color:red;" title="Campo obrigatório">*</label>
            <div class="ui-widget">
                @Html.EditorFor(model => model.Cpf, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cpf, "", new { @class = "text-danger" })
            </div>
        </div>

        <h4 class="ui dividing header" style="width: 100%">Contatos</h4>
        <div class="form-group col-md-4">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label" })
            <label style="color:red;" title="Campo obrigatório">*</label>
            <div class="ui-widget">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group col-md-2">
            @Html.LabelFor(model => model.TelefoneFixo, htmlAttributes: new { @class = "control-label" })
            <div class="ui-widget">
                @Html.EditorFor(model => model.TelefoneFixo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TelefoneFixo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group col-md-2">
            @Html.LabelFor(model => model.TelefoneMovel, htmlAttributes: new { @class = "control-label" })
            <div class="ui-widget">
                @Html.EditorFor(model => model.TelefoneMovel, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TelefoneMovel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group col-md-4">
            @Html.LabelFor(model => model.Foto, htmlAttributes: new { @class = "control-label" })
            <div class="ui-widget">
                @Html.TextBoxFor(model => model.Foto, new { type = "file", @class = "form-control-file" })
                @Html.ValidationMessageFor(model => model.Foto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group col-md-4">
            <div class="ui checkbox">
                @Html.EditorFor(model => model.Ativo, new { @type = "checkbox" })
                @Html.LabelFor(model => model.Ativo, null, htmlAttributes: new { @class = "control-label" })
                @Html.ValidationMessageFor(model => model.Ativo, "", new { @class = "text-danger" })
            </div>
        </div>

        <h4 class="ui dividing header" style="width: 100%">Localização</h4>
        <div class="form-group col-md-3">
            @Html.LabelFor(model => model.Pais_Id, htmlAttributes: new { @class = "control-label" })
            <label style="color:red;" title="Campo obrigatório">*</label>
            <div class="ui-widget">
                @Html.DropDownList("Pais_Id", null, new { @class = "ui fluid search selection dropdown" })
                @Html.ValidationMessageFor(model => model.Pais_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group col-md-3">
            @Html.LabelFor(model => model.Estado_Id, htmlAttributes: new { @class = "control-label" })
            <label style="color:red;" title="Campo obrigatório">*</label>
            <div class="ui-widget">
                @Html.DropDownList("Estado_Id", null, new { @class = "ui fluid search selection dropdown" })
                @Html.ValidationMessageFor(model => model.Estado_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group col-md-3">
            @Html.LabelFor(model => model.Cidade_Id, htmlAttributes: new { @class = "control-label" })
            <label class="text-danger" title="Campo obrigatório">*</label>
            <div class="ui-widget">
                @Html.DropDownList("Cidade_Id", null, new { @class = "ui fluid search selection dropdown" })
                @Html.ValidationMessageFor(model => model.Cidade_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group col-md-3">
            @Html.LabelFor(model => model.Bairro_Id, htmlAttributes: new { @class = "control-label" })
            <label style="color:red;" title="Campo obrigatório">*</label>
            <div class="ui-widget">
                @Html.DropDownList("Bairro_Id", null, new { @class = "ui fluid search selection dropdown" })
                @Html.ValidationMessageFor(model => model.Bairro_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group col-md-3">
            @Html.LabelFor(model => model.Logradouro_Id, htmlAttributes: new { @class = "control-label" })
            <label style="color:red;" title="Campo obrigatório">*</label>
            <div class="ui-widget">
                @Html.DropDownList("Logradouro_Id", null, new { @class = "ui fluid search selection dropdown" })
                @Html.ValidationMessageFor(model => model.Logradouro_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group col-md-2">
            @Html.LabelFor(model => model.Cep, htmlAttributes: new { @class = "control-label" })
            <div class="ui-widget">
                @Html.EditorFor(model => model.Cep, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cep, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group col-md-1">
            @Html.LabelFor(model => model.Numero, htmlAttributes: new { @class = "control-label" })
            <div class="ui-widget">
                @Html.EditorFor(model => model.Numero, new { htmlAttributes = new { @class = "form-control numero_residencial" } })
                @Html.ValidationMessageFor(model => model.Numero, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group col-md-6">
            @Html.LabelFor(model => model.Complemento, htmlAttributes: new { @class = "control-label" })
            <div class="ui-widget">
                @Html.EditorFor(model => model.Complemento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Complemento, "", new { @class = "text-danger" })
            </div>
        </div>

        <h4 class="ui dividing header" style="width: 100%">Cadastro <label style="color:red">(Opcional)</label></h4>
        <div class="form-group col-md-">
            @Html.LabelFor(model => model.Login, htmlAttributes: new { @class = "control-label" })
            <div class="ui-widget">
                @Html.EditorFor(model => model.Login, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Login, string.Empty, new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group col-md-4 col-sm-12">
            @Html.LabelFor(model => model.Senha, htmlAttributes: new { @class = "control-label" })
            <div class="ui-widget">
                @Html.EditorFor(model => model.Senha, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Senha, string.Empty, new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group col-md-4 col-sm-12">
            @Html.LabelFor(model => model.ValidaSenha, htmlAttributes: new { @class = "control-label" })
            <div class="ui-widget">
                @Html.EditorFor(model => model.ValidaSenha, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ValidaSenha, string.Empty, new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group col-md-4 col-sm-12">
            <div class="ui checkbox" style="margin-top:37px">
                @Html.EditorFor(model => model.AlterarSenha, new { @type = "checkbox" })
                @Html.LabelFor(model => model.AlterarSenha, null, htmlAttributes: new { @class = "control-label" })
                @Html.ValidationMessageFor(model => model.AlterarSenha, "", new { @class = "text-danger" })
            </div>
        </div>

    </div>
    <div class="form-group col-12">
        <div class="col-md-offset-2">
            <input type="submit" value="Salvar" class="ui violet button" />
        </div>
    </div>
}

PrismaWEB.MVC/Views/Pessoas/Details.cshtml
@model ProjetoModeloDDD.MVC.ViewModels.PessoaViewModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>PessoaViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataNascimento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataNascimento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cpf)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cpf)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Foto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Foto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ativo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ativo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Apelido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Apelido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TelefoneFixo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TelefoneFixo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TelefoneMovel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TelefoneMovel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pais_Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pais_Id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estado_Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estado_Id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cidade_Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cidade_Id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Bairro_Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Bairro_Id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Logradouro_Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Logradouro_Id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cep)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cep)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Numero)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Numero)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Complemento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Complemento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tipo_Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tipo_Id)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

PrismaWEB.MVC/Views/Pessoas/Index.cshtml
@model IEnumerable<ProjetoModeloDDD.MVC.ViewModels.PessoaViewModel>

@using ProjetoModeloDDD.MVC.Html_Helpers

@{
    ViewBag.Title = "Index";
}

@{
    Html.RenderAction("BotaoCreate", "Botoes", new { NomeController = "Pessoas"});
}
<div class="card-body">
    <div class="table-responsive">
        <table class="table table-bordered" id="dataTable" cellspacing="0">
            <thead>
                <tr>
                    <th>Ações</th>
                    <th>
                        @Html.DisplayNameFor(model => model.Nome)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.DataNascimento)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Cpf)
                    </th>
                </tr>
            </thead>

            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td style="width:90px">
                            @Html.Editar(item.Id, Url.Action("Edit", new { id = item.Id }))
                            @Html.Deletar(item.Id, item.Nome)
                            @if (item.Ativo == true)
                            {
                                <a href="@Url.Action("Desativar", new { id = item.Id })" data-toggle="tooltip" title="Desativar">
                                    <span style="margin-right:0px;" class="ban">
                                        <i class="fa fa-share-square" aria-hidden="true" style="color:white"></i>
                                    </span>
                                </a>
                            }
                            else
                            {
                                <a href="@Url.Action("Ativar", new { id = item.Id })" data-toggle="tooltip" title="Ativar">
                                    <span style="margin-right:0px;" class="green">
                                        <i class="fa fa-check-square" aria-hidden="true" style="color:white"></i>
                                    </span>
                                </a>
                            }
                        </td>
                        <td>
                            <a href="@Url.Action("Details/"+item.Id)" class="removeLinkAzul">
                                @Html.DisplayFor(modelItem => item.Nome)
                            </a>
                        </td>
                        <td>
                            <a href="@Url.Action("Details/"+item.Id)" class="removeLinkAzul">
                                @item.DataNascimento.ToString("dd/MM/yyyy")
                            </a>
                        </td>
                        <td>
                            <a href="@Url.Action("Details/"+item.Id)" class="removeLinkAzul">
                                @Html.DisplayFor(modelItem => item.Cpf)

                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>
<div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>